"""init database

Revision ID: 22f993cffca6
Revises: 
Create Date: 2025-07-29 04:47:11.318730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '22f993cffca6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('keywords',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('hotness_score', sa.BigInteger(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('keyword_id', sa.BigInteger(), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('ai_model_used', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('final_prompt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('article_generation_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('keyword_id', sa.BigInteger(), nullable=False),
    sa.Column('article_id', sa.BigInteger(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('ai_model_used', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('final_prompt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_generation_logs')
    op.drop_table('articles')
    op.drop_table('keywords')
    # ### end Alembic commands ###
